#!/usr/bin/env python
# coding: utf-8

# In[1]:


import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import lime
from lime import lime_tabular
import datetime



import warnings
warnings.filterwarnings('ignore')


# In[2]:


train=pd.read_csv("Training.csv")
test=pd.read_csv("Testing.csv")


# In[6]:


train=train.drop(["Unnamed: 133"],axis=1)


# In[17]:


P = train[["prognosis"]]
X = train.drop(["prognosis"],axis=1)
Y = test.drop(["prognosis"],axis=1)


# In[18]:


from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(X,P,test_size=0.2,random_state=42)


# In[19]:


from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score


# In[20]:


rf= RandomForestClassifier(random_state=42)
model_rf = rf.fit(xtrain,ytrain)
tr_pred_rf = model_rf.predict(xtrain)
ts_pred_rf = model_rf.predict(xtest)


# In[21]:


def predict_disease(model, attributes):
    # Create a DataFrame with the input attributes
    input_data = pd.DataFrame([attributes], columns=X.columns)
    
    # Make predictions
    predicted_disease = model.predict(input_data)
    
    return predicted_disease[0]  # Return the predicted disease name


# In[22]:

import sys


input_symptoms = sys.argv[1]

# Convert input symptoms to integers
input_attributes=[]
for i in range(132):
    input_attributes.append(0)
syy=['itching', 'skin_rash', 'nodal_skin_eruptions', 'continuous_sneezing', 'shivering', 'chills', 'joint_pain', 'stomach_pain', 'acidity', 'ulcers_on_tongue', 'muscle_wasting', 'vomiting', 'burning_micturition', 'spotting_urination', 'fatigue', 'weight_gain', 'anxiety', 'cold_hands_and_feets', 'mood_swings', 'weight_loss', 'restlessness', 'lethargy', 'patches_in_throat', 'irregular_sugar_level', 'cough', 'high_fever', 'sunken_eyes', 'breathlessness', 'sweating', 'dehydration', 'indigestion', 'headache', 'yellowish_skin', 'dark_urine', 'nausea', 'loss_of_appetite', 'pain_behind_the_eyes', 'back_pain', 'constipation', 'abdominal_pain', 'diarrhoea', 'mild_fever', 'yellow_urine', 'yellowing_of_eyes', 'acute_liver_failure', 'fluid_overload', 'swelling_of_stomach', 'swelled_lymph_nodes', 'malaise', 'blurred_and_distorted_vision', 'phlegm', 'throat_irritation', 'redness_of_eyes', 'sinus_pressure', 'runny_nose', 'congestion', 'chest_pain', 'weakness_in_limbs', 'fast_heart_rate', 'pain_during_bowel_movements', 'pain_in_anal_region', 'bloody_stool', 'irritation_in_anus', 'neck_pain', 'dizziness', 'cramps', 'bruising', 'obesity', 'swollen_legs', 'swollen_blood_vessels', 'puffy_face_and_eyes', 'enlarged_thyroid', 'brittle_nails', 'swollen_extremeties', 'excessive_hunger', 'extra_marital_contacts', 'drying_and_tingling_lips', 'slurred_speech', 'knee_pain', 'hip_joint_pain', 'muscle_weakness', 'stiff_neck', 'swelling_joints', 'movement_stiffness', 'spinning_movements', 'loss_of_balance', 'unsteadiness', 'weakness_of_one_body_side', 'loss_of_smell', 'bladder_discomfort', 'foul_smell_of_urine', 'continuous_feel_of_urine', 'passage_of_gases', 'internal_itching', 'toxic_look_(typhos)', 'depression', 'irritability', 'muscle_pain', 'altered_sensorium', 'red_spots_over_body', 'belly_pain', 'abnormal_menstruation', 'dischromic_patches', 'watering_from_eyes', 'increased_appetite', 'polyuria', 'family_history', 'mucoid_sputum', 'rusty_sputum', 'lack_of_concentration', 'visual_disturbances', 'receiving_blood_transfusion', 'receiving_unsterile_injections', 'coma', 'stomach_bleeding', 'distention_of_abdomen', 'history_of_alcohol_consumption', 'fluid_overload', 'blood_in_sputum', 'prominent_veins_on_calf', 'palpitations', 'painful_walking', 'pus_filled_pimples', 'blackheads', 'scurring', 'skin_peeling', 'silver_like_dusting', 'small_dents_in_nails', 'inflammatory_nails', 'blister', 'red_sore_around_nose', 'yellow_crust_ooze']
disease_dict = {
    'Fungal infection': "Fungal infections are caused by various types of fungi and can affect different parts of the body, including the skin, nails, and genitals. Prevention involves maintaining good personal hygiene, keeping skin dry and clean, wearing breathable clothing, and avoiding sharing personal items such as towels and clothing. Treatment typically includes antifungal medications, either topical creams or oral medications, prescribed by a healthcare professional. It's important to complete the full course of treatment to prevent recurrence. In severe cases or when the infection doesn't respond to standard treatments, additional therapies such as laser therapy or surgical removal may be necessary. Prevention is key, especially for individuals with weakened immune systems or those who frequently come into contact with fungi, such as athletes or individuals with diabetes.",

    'Allergy': "Allergies occur when the immune system overreacts to a harmless substance, triggering symptoms such as sneezing, itching, and watery eyes. Preventive measures include identifying and avoiding allergens whenever possible, such as pollen, pet dander, dust mites, and certain foods. Maintaining a clean indoor environment, using air purifiers, and regularly washing bedding can help reduce allergen exposure. Allergy testing by a healthcare professional can identify specific triggers, allowing for targeted avoidance strategies. Treatment options include over-the-counter antihistamines, nasal corticosteroids, and decongestants to alleviate symptoms. In severe cases, allergen immunotherapy (allergy shots) may be recommended to desensitize the immune system to specific allergens. Lifestyle changes, such as quitting smoking and managing stress, can also help reduce allergy symptoms and improve overall quality of life.",

    'GERD': "Gastroesophageal reflux disease (GERD) is a chronic condition where stomach acid flows back into the esophagus, leading to symptoms such as heartburn, chest pain, and difficulty swallowing. Prevention involves adopting lifestyle changes such as maintaining a healthy weight, avoiding trigger foods like spicy or acidic foods, and eating smaller, more frequent meals. Elevating the head of the bed and avoiding lying down immediately after meals can help reduce acid reflux. Dietary modifications, such as limiting caffeine and alcohol consumption, and quitting smoking can also alleviate symptoms. Treatment options include over-the-counter antacids, proton pump inhibitors (PPIs), and H2-receptor antagonists to reduce stomach acid production. In severe cases or when lifestyle modifications and medications are ineffective, surgical procedures such as fundoplication may be recommended to strengthen the lower esophageal sphincter and prevent acid reflux.",

    'Chronic cholestasis': "Chronic cholestasis is a condition characterized by impaired bile flow from the liver, leading to the accumulation of bile acids and toxins in the liver and bloodstream. Prevention involves maintaining a healthy lifestyle, including a balanced diet rich in fruits, vegetables, and whole grains while limiting saturated fats and processed foods. Avoiding excessive alcohol consumption is crucial for liver health, as alcohol can exacerbate cholestasis and liver damage. Regular exercise and weight management can also support liver function. Treatment options depend on the underlying cause of cholestasis and may include medications to improve bile flow, manage symptoms, and prevent complications such as liver failure. In some cases, liver transplantation may be necessary for individuals with advanced liver disease or cirrhosis. Close monitoring by a healthcare provider is essential for managing chronic cholestasis and optimizing liver health.",

    'Drug Reaction': "Drug reactions can range from mild skin rashes to life-threatening allergic reactions and are caused by a variety of medications, including prescription drugs, over-the-counter medications, and herbal supplements. Prevention involves communicating openly with healthcare providers about any known drug allergies, sensitivities, or previous adverse reactions. Patients should read medication labels carefully, follow dosage instructions precisely, and report any unusual symptoms to their healthcare provider promptly. Avoiding the use of expired or counterfeit medications and being cautious when trying new medications can help reduce the risk of drug reactions. Treatment for drug reactions depends on the severity and type of reaction and may include discontinuing the offending medication, supportive care to manage symptoms, and in severe cases, administration of corticosteroids or epinephrine to control allergic reactions. Patients with a history of drug reactions should wear a medical alert bracelet or carry an emergency epinephrine auto-injector to alert healthcare providers in case of a medical emergency.",

    'Peptic ulcer disease': "Peptic ulcer disease (PUD) refers to open sores that develop on the lining of the stomach, small intestine, or esophagus, often due to infection with Helicobacter pylori bacteria or long-term use of nonsteroidal anti-inflammatory drugs (NSAIDs). Prevention involves avoiding known risk factors, such as smoking, excessive alcohol consumption, and regular use of NSAIDs. Dietary modifications, such as eating smaller, more frequent meals and avoiding spicy or acidic foods, can help reduce irritation to the stomach lining. Treatment typically includes a combination of antibiotics to eradicate H. pylori infection, proton pump inhibitors (PPIs) or H2-receptor antagonists to reduce stomach acid production, and antacids to relieve symptoms. In severe cases or when complications such as bleeding or perforation occur, hospitalization and surgical interventions may be necessary to repair the ulcer and prevent further complications. Lifestyle changes, such as stress management and maintaining a healthy weight, can also support ulcer healing and prevent recurrence.",

    'AIDS': "Acquired immunodeficiency syndrome (AIDS) is a chronic condition caused by the human immunodeficiency virus (HIV), which weakens the immune system and increases susceptibility to opportunistic infections and certain cancers. Prevention strategies include practicing safe sex, using barrier methods such as condoms, and avoiding sharing needles or other injection equipment. HIV testing and counseling can help identify individuals at risk and provide early access to treatment and preventive measures. Treatment involves antiretroviral therapy (ART), a combination of medications that suppress HIV replication and restore immune function. Adherence to ART is essential for maintaining viral suppression and preventing disease progression. Pre-exposure prophylaxis (PrEP) is recommended for individuals at high risk of HIV infection, such as serodiscordant couples or individuals with multiple partners. Regular medical monitoring, including viral load and CD4 count tests, is necessary to assess treatment effectiveness and detect any complications early.",

    'Diabetes': "Diabetes mellitus is a chronic metabolic disorder characterized by high blood sugar levels due to insufficient insulin production or ineffective use of insulin by the body. Prevention strategies include maintaining a healthy weight through regular exercise and a balanced diet rich in fruits, vegetables, and whole grains while limiting sugar and processed foods. Screening for prediabetes and early detection of diabetes risk factors, such as family history or obesity, can help initiate preventive measures and lifestyle modifications. Treatment involves a combination of lifestyle changes, including dietary modifications and physical activity, and medication management to achieve and maintain blood sugar control. Insulin therapy may be necessary for individuals with type 1 diabetes or advanced type 2 diabetes. Regular monitoring of blood sugar levels, along with routine medical check-ups to assess kidney function, eye health, and cardiovascular risk, is essential for diabetes management and prevention of complications.",

    'Gastroenteritis': "Gastroenteritis is an inflammation of the stomach and intestines, commonly caused by viral or bacterial infections transmitted through contaminated food or water, poor hygiene practices, or close contact with infected individuals. Prevention strategies include practicing good hygiene, such as frequent handwashing with soap and water, especially before eating and after using the bathroom. Proper food handling and preparation, such as cooking meats thoroughly and avoiding cross-contamination, can reduce the risk of gastroenteritis. Vaccination against rotavirus, a common cause of viral gastroenteritis in infants and young children, is recommended as part of routine childhood immunization. Treatment focuses on supportive care, such as fluid and electrolyte replacement to prevent dehydration, along with symptomatic relief of nausea, vomiting, and diarrhea. In severe cases or when dehydration is significant, hospitalization and intravenous fluids may be necessary. Antibiotics are not usually recommended for viral gastroenteritis and should only be used for bacterial gastroenteritis under medical supervision.",

    'Bronchial Asthma': "Bronchial asthma is a chronic respiratory condition characterized by inflammation and narrowing of the airways, leading to symptoms such as wheezing, coughing, shortness of breath, and chest tightness. Prevention strategies include identifying and avoiding triggers that exacerbate asthma symptoms, such as allergens (e.g., pollen, pet dander, dust mites), air pollutants (e.g., tobacco smoke, car exhaust), respiratory infections, and cold air. Regular use of controller medications, such as inhaled corticosteroids or leukotriene modifiers, can help reduce airway inflammation and prevent asthma attacks. Quick-relief medications, such as short-acting beta-agonists (SABAs) and anticholinergics, provide rapid relief of acute symptoms during asthma exacerbations. Asthma action plans, developed in collaboration with healthcare providers, outline personalized treatment strategies and emergency response measures to manage asthma effectively. Regular monitoring of lung function with peak flow meters or spirometry helps assess asthma control and adjust treatment accordingly. Education and self-management skills training empower individuals with asthma to recognize early warning signs, adhere to treatment plans, and minimize the impact of asthma on daily life.",

    'Hypertension': "Hypertension, or high blood pressure, is a common cardiovascular condition characterized by elevated blood pressure levels persistently exceeding 130/80 mmHg. Prevention involves adopting a heart-healthy lifestyle, including maintaining a healthy weight, following a balanced diet low in sodium and saturated fats, limiting alcohol consumption, and engaging in regular physical activity. Regular monitoring of blood pressure and routine medical check-ups can help identify hypertension early and initiate appropriate interventions. Treatment aims to lower blood pressure to target levels and reduce the risk of cardiovascular complications such as heart attacks, strokes, and kidney disease. Lifestyle modifications, including dietary changes, increased physical activity, and stress management techniques, are recommended as first-line therapy for mild hypertension. Medications such as diuretics, ACE inhibitors, angiotensin II receptor blockers (ARBs), beta-blockers, calcium channel blockers, and other antihypertensive agents may be prescribed to achieve blood pressure control. Individualized treatment plans, based on patient preferences, comorbidities, and drug tolerability, are essential for optimizing hypertension management and reducing cardiovascular risk.",

    'Migraine': "Migraine is a neurological disorder characterized by recurrent episodes of moderate to severe headaches, often accompanied by symptoms such as nausea, vomiting, and sensitivity to light and sound. Prevention strategies include identifying and avoiding triggers that precipitate migraine attacks, such as certain foods (e.g., aged cheeses, processed meats), hormonal fluctuations, stress, sleep disturbances, and environmental factors (e.g., bright lights, strong odors). Establishing regular sleep patterns, staying hydrated, and practicing relaxation techniques, such as deep breathing exercises or mindfulness meditation, can help reduce migraine frequency and severity. Treatment options for acute migraine attacks include over-the-counter or prescription medications, such as nonsteroidal anti-inflammatory drugs (NSAIDs), triptans, ergotamines, and anti-nausea medications. For individuals with frequent or severe migraines, preventive medications such as beta-blockers, calcium channel blockers, tricyclic antidepressants, anticonvulsants, or CGRP monoclonal antibodies may be recommended to reduce migraine frequency and improve quality of life. Lifestyle modifications, including regular exercise, balanced nutrition, and stress management, complement pharmacological therapies and promote overall well-being for individuals with migraine.",
        'Cervical spondylosis': "Cervical spondylosis, also known as neck arthritis or cervical osteoarthritis, is a degenerative condition affecting the cervical spine, characterized by the breakdown of vertebral discs and the formation of bone spurs in the neck. Prevention strategies focus on maintaining good posture, avoiding prolonged neck strain, and practicing neck exercises to strengthen muscles and improve flexibility. Ergonomic adjustments, such as using supportive pillows and chairs, and taking regular breaks during activities that strain the neck, can help prevent exacerbation of symptoms. Treatment options for cervical spondylosis include conservative measures such as physical therapy, heat or ice therapy, and pain-relieving medications like nonsteroidal anti-inflammatory drugs (NSAIDs) or muscle relaxants to alleviate pain and inflammation. In cases of severe or persistent symptoms, corticosteroid injections may provide short-term relief by reducing inflammation around the affected nerves. Surgical interventions, such as cervical discectomy or cervical fusion, may be considered for individuals with progressive neurological deficits or severe pain that does not respond to conservative treatments. Lifestyle modifications, including regular exercise, maintaining a healthy weight, and avoiding smoking, can help slow the progression of cervical spondylosis and improve overall neck health.",

    'Paralysis (brain hemorrhage)': "Paralysis resulting from brain hemorrhage occurs when bleeding in the brain damages or impairs the function of the nerves responsible for controlling movement and sensation. Prevention strategies focus on managing modifiable risk factors for brain hemorrhage, such as hypertension, smoking, excessive alcohol consumption, and illicit drug use. Regular monitoring of blood pressure and adherence to antihypertensive medications can help reduce the risk of hemorrhagic strokes. Lifestyle modifications, including following a heart-healthy diet, engaging in regular physical activity, and maintaining a healthy weight, can also lower the risk of stroke and associated complications. Treatment for paralysis resulting from brain hemorrhage depends on the extent and location of the bleeding, as well as the severity of neurological deficits. Immediate medical intervention, including surgical procedures such as craniotomy or endovascular coiling, may be necessary to stop the bleeding and relieve pressure on the brain. Rehabilitation therapy, including physical therapy, occupational therapy, and speech therapy, plays a crucial role in maximizing functional recovery and improving quality of life for individuals with paralysis. Assistive devices, mobility aids, and home modifications may be recommended to support independent living and enhance accessibility for individuals with paralysis.",

    'Jaundice': "Jaundice, characterized by yellowing of the skin and whites of the eyes, occurs when there is an excess of bilirubin in the blood, often due to liver dysfunction or obstruction of the bile ducts. Prevention strategies for jaundice focus on maintaining liver health and preventing underlying liver conditions that can lead to jaundice, such as viral hepatitis, alcoholic liver disease, and cirrhosis. Avoiding excessive alcohol consumption, practicing safe sex to prevent hepatitis transmission, and getting vaccinated against hepatitis A and B viruses can reduce the risk of viral hepatitis. Treatment for jaundice depends on the underlying cause and may include addressing liver dysfunction or treating infections or obstructions that impair bile flow. In cases of viral hepatitis, antiviral medications may be prescribed to suppress viral replication and prevent liver damage. Supportive measures such as rest, hydration, and nutritional support can help alleviate symptoms and promote recovery. In severe cases of liver failure or bile duct obstruction, surgical interventions such as liver transplantation or bile duct drainage may be necessary to restore liver function and improve outcomes. Lifestyle modifications, including maintaining a healthy diet, exercising regularly, and avoiding alcohol and hepatotoxic medications, can help prevent jaundice and promote overall liver health.",

    'Malaria': "Malaria is a life-threatening mosquito-borne disease caused by Plasmodium parasites, transmitted through the bite of infected Anopheles mosquitoes. Prevention strategies for malaria include personal protective measures, such as using insect repellents, wearing long-sleeved clothing, and sleeping under insecticide-treated bed nets, especially during peak mosquito biting hours. Chemoprophylaxis with antimalarial medications is recommended for travelers to malaria-endemic regions to prevent infection. Environmental interventions, such as mosquito control measures like larviciding and insecticide spraying, can help reduce mosquito populations and minimize transmission. Early diagnosis and prompt treatment of malaria are essential for preventing severe complications and reducing mortality. Antimalarial medications, such as artemisinin-based combination therapies (ACTs), are used to treat malaria and clear the parasite from the bloodstream. In areas with multidrug-resistant malaria, alternative antimalarial drugs may be prescribed. Health education and community engagement efforts play a critical role in promoting malaria prevention and control, including raising awareness about the importance of seeking timely medical care, adhering to treatment regimens, and participating in vector control activities.",

    'Chicken pox': "Chickenpox, caused by the varicella-zoster virus (VZV), is a highly contagious viral infection characterized by a rash of itchy, fluid-filled blisters that eventually crust over. Prevention of chickenpox involves vaccination with the varicella vaccine, which is recommended as part of routine childhood immunization schedules. Vaccination not only protects individuals from chickenpox but also reduces the risk of severe complications such as pneumonia, encephalitis, and bacterial skin infections. Vaccination is also recommended for susceptible adults who have not had chickenpox or received the vaccine previously. Avoiding close contact with infected individuals and practicing good hygiene, such as frequent handwashing, can help prevent the spread of chickenpox. Treatment for chickenpox focuses on relieving symptoms and preventing complications. Over-the-counter antihistamines and topical calamine lotion can help alleviate itching and soothe skin irritation. Acetaminophen or ibuprofen may be used to reduce fever and relieve pain. Antiviral medications such as acyclovir or valacyclovir may be prescribed for individuals at high risk of severe disease or complications, including immunocompromised individuals or adults with varicella.",

    'Dengue': "Dengue fever is a mosquito-borne viral illness caused by the dengue virus, transmitted primarily by Aedes mosquitoes. Prevention of dengue fever focuses on reducing mosquito breeding sites and minimizing mosquito bites. Measures to prevent mosquito breeding include eliminating standing water in containers, using larvicides to treat water storage containers, and covering or emptying outdoor water containers regularly. Personal protective measures to prevent mosquito bites include using insect repellents containing DEET or picaridin, wearing long-sleeved clothing and long pants, and using mosquito nets while sleeping in areas with high mosquito activity. Integrated vector control strategies, including community engagement and environmental management, are essential for reducing mosquito populations and interrupting dengue transmission. Early detection and prompt medical care are crucial for managing dengue fever and preventing severe complications such as dengue hemorrhagic fever or dengue shock syndrome. Supportive care, including hydration therapy, rest, and pain relief, can help alleviate symptoms and improve outcomes for individuals with dengue fever. Health education and community mobilization efforts play a vital role in raising awareness about dengue prevention and control measures, promoting community participation, and empowering individuals to take proactive steps to reduce dengue transmission.",

        'Typhoid': "Typhoid fever is a bacterial infection caused by Salmonella typhi bacteria, transmitted through contaminated food and water or by close contact with infected individuals. Prevention of typhoid fever involves measures to ensure food and water safety, including consuming only boiled or bottled water, avoiding raw or undercooked foods, and practicing good hand hygiene, especially before handling food or eating. Vaccination with the typhoid vaccine is recommended for travelers to regions where typhoid fever is endemic and for individuals at increased risk of exposure to the bacteria, such as healthcare workers or laboratory personnel. Health education and community-based interventions can raise awareness about the importance of hygiene practices, safe food handling, and vaccination to prevent typhoid fever transmission. Treatment for typhoid fever typically involves antibiotics to eliminate the bacteria from the body and alleviate symptoms. Commonly prescribed antibiotics include fluoroquinolones, azithromycin, or third-generation cephalosporins. Supportive care, including hydration therapy and fever management, can help alleviate symptoms and promote recovery. In severe cases or when complications such as intestinal perforation occur, hospitalization and surgical interventions may be necessary. Timely diagnosis, appropriate antibiotic treatment, and adherence to preventive measures are essential for controlling typhoid fever outbreaks and reducing morbidity and mortality rates.",

    'Hepatitis A': "Hepatitis A is a viral liver infection caused by the hepatitis A virus (HAV), transmitted primarily through the ingestion of contaminated food or water or by close contact with an infected person. Prevention of hepatitis A involves vaccination with the hepatitis A vaccine, which provides long-term protection against the virus and is recommended as part of routine childhood immunization schedules in many countries. Vaccination is also recommended for individuals at increased risk of hepatitis A infection, including travelers to regions with high hepatitis A incidence, men who have sex with men, and individuals with chronic liver disease or HIV infection. Practicing good hygiene, including frequent handwashing with soap and water, and avoiding consumption of raw or undercooked shellfish or contaminated food and water sources, can help prevent hepatitis A transmission. Health education campaigns and community-based interventions can raise awareness about hepatitis A prevention measures and promote vaccination uptake. Treatment for hepatitis A is supportive and focuses on alleviating symptoms, such as fatigue, nausea, and jaundice. Rest, hydration therapy, and avoiding alcohol and hepatotoxic medications are recommended to support liver function and promote recovery. Most people with hepatitis A recover fully without complications, but in rare cases, severe liver damage or fulminant hepatitis may occur, requiring hospitalization and intensive medical care.",

    'Hepatitis B': "Hepatitis B is a viral liver infection caused by the hepatitis B virus (HBV), transmitted through contact with infected blood or other bodily fluids, including sexual contact, sharing of needles or syringes, and perinatal transmission from mother to child. Prevention of hepatitis B involves vaccination with the hepatitis B vaccine, which provides long-term protection against HBV infection and is recommended as part of routine childhood immunization schedules worldwide. Vaccination is also recommended for individuals at increased risk of HBV infection, including healthcare workers, people with multiple sexual partners, injection drug users, and household contacts of HBV-infected individuals. Practicing safe sex, using barrier methods such as condoms, and avoiding sharing needles or other injection equipment can help prevent HBV transmission. Health education campaigns and community-based interventions can raise awareness about hepatitis B prevention measures and promote vaccination uptake. Treatment for chronic hepatitis B aims to suppress viral replication, reduce liver inflammation, and prevent disease progression. Antiviral medications, such as nucleoside or nucleotide analogs and interferon-alpha, may be prescribed to control HBV replication and minimize liver damage. Regular monitoring of liver function tests and viral load levels is necessary to assess treatment effectiveness and adjust therapy as needed. In some cases, liver transplantation may be considered for individuals with advanced liver disease or hepatocellular carcinoma (liver cancer) associated with chronic hepatitis B.",

    'Hepatitis C': "Hepatitis C is a viral liver infection caused by the hepatitis C virus (HCV), transmitted primarily through contact with infected blood, including sharing needles or other injection equipment, receiving contaminated blood transfusions or organ transplants, and perinatal transmission from mother to child. Prevention of hepatitis C focuses on reducing the risk of HCV transmission through harm reduction strategies, such as needle exchange programs, opioid agonist therapy for individuals with substance use disorders, and screening of blood donors and organ donors for HCV infection. Health education campaigns and community-based interventions can raise awareness about hepatitis C prevention measures and promote safer injection practices and bloodborne pathogen precautions. There is currently no vaccine available for hepatitis C. Treatment for hepatitis C has undergone significant advancements in recent years with the development of direct-acting antiviral medications that target specific steps in the HCV replication cycle. These antiviral drugs, administered orally as part of interferon-free regimens, have high efficacy rates and minimal side effects, leading to cure rates exceeding 95% in most cases. Treatment duration and choice of antiviral regimen depend on various factors, including HCV genotype, extent of liver fibrosis, and prior treatment history. Close monitoring of liver function tests and viral load levels is necessary during and after treatment to assess treatment response and ensure sustained virologic response (SVR), indicating viral clearance and cure of hepatitis C infection.",

    'Hepatitis D': "Hepatitis D, also known as delta hepatitis, is a viral liver infection caused by the hepatitis D virus (HDV), which requires the presence of hepatitis B virus (HBV) for replication and transmission. Prevention of hepatitis D involves strategies to prevent HBV infection, as HDV can only infect individuals who are already infected with HBV. Therefore, vaccination against hepatitis B is the primary preventive measure for hepatitis D. The hepatitis B vaccine provides long-term protection against HBV infection and is recommended as part of routine childhood immunization schedules worldwide. Vaccination is also recommended for individuals at increased risk of HBV infection, including healthcare workers, people with multiple sexual partners, injection drug users, and household contacts of HBV-infected individuals. Practicing safe sex, using barrier methods such as condoms, and avoiding sharing needles or other injection equipment can help prevent HBV transmission and subsequently reduce the risk of hepatitis D. Health education campaigns and community-based interventions can raise awareness about hepatitis B prevention measures and promote vaccination uptake. Treatment for hepatitis D is challenging, as there are currently no specific antiviral medications approved for HDV infection. Management typically involves controlling HBV replication with antiviral medications such as nucleoside or nucleotide analogs, which may also have activity against HDV. Liver transplantation may be considered for individuals with advanced liver disease or decompensated cirrhosis associated with hepatitis D.",

    'Hepatitis E': "Hepatitis E is a viral liver infection caused by the hepatitis E virus (HEV), transmitted primarily through the fecal-oral route via contaminated food or water sources or by close contact with infected individuals. Prevention of hepatitis E focuses on ensuring food and water safety, practicing good personal hygiene, and implementing sanitation measures to prevent fecal contamination of water supplies and food products. Boiling or treating water with chlorine or iodine tablets can help inactivate HEV and reduce the risk of transmission. Avoiding consumption of raw or undercooked shellfish, unpasteurized dairy products, and contaminated fruits and vegetables can also help prevent hepatitis E infection. Health education campaigns and community-based interventions can raise awareness about hepatitis E prevention measures and promote hygiene practices, safe food handling, and environmental sanitation. There is currently no vaccine available for hepatitis E. Treatment for hepatitis E is primarily supportive and focuses on alleviating symptoms, such as fatigue, nausea, and jaundice. Rest, hydration therapy, and avoiding alcohol and hepatotoxic medications are recommended to support liver function and promote recovery. Most people with hepatitis E recover fully without complications, but in rare cases, severe acute liver failure may occur, requiring hospitalization and supportive care.",

    'Alcoholic hepatitis': "Alcoholic hepatitis is a liver inflammation caused by excessive alcohol consumption, leading to liver damage and dysfunction. Prevention of alcoholic hepatitis involves reducing or abstaining from alcohol consumption to minimize the risk of liver damage and other alcohol-related complications. Drinking alcohol in moderation, following recommended guidelines for alcohol consumption, and avoiding binge drinking can help prevent alcoholic liver disease, including alcoholic hepatitis. Health education campaigns and community-based interventions can raise awareness about the health risks of excessive alcohol consumption and promote alcohol screening and counseling services for individuals at risk. Treatment for alcoholic hepatitis focuses on abstinence from alcohol and supportive care to manage symptoms and prevent complications. Complete cessation of alcohol consumption is essential to prevent further liver damage and improve liver function. Nutritional support, including a well-balanced diet with adequate protein and calories, and vitamin supplementation, particularly with thiamine (vitamin B1), can help support liver regeneration and improve outcomes. Corticosteroids or pentoxifylline may be prescribed to reduce liver inflammation and improve survival in severe cases of alcoholic hepatitis. In some cases, liver transplantation may be considered for individuals with advanced liver disease or acute liver failure associated with alcoholic hepatitis.",

    'Tuberculosis': "Tuberculosis (TB) is a bacterial infection caused by Mycobacterium tuberculosis, typically affecting the lungs but can also involve other organs and tissues. Prevention of tuberculosis involves a combination of public health measures, such as early detection and treatment of active TB cases, and strategies to reduce TB transmission, including infection control measures and vaccination. The Bacillus Calmette-Guérin (BCG) vaccine, administered to newborns in many countries with high TB prevalence, provides partial protection against severe forms of TB, such as TB meningitis and disseminated TB in young children. In high TB burden settings, preventive therapy with isoniazid (INH) for individuals at increased risk of TB infection or progression, such as household contacts of TB patients, HIV-positive individuals, and individuals with latent TB infection, can help reduce the risk of developing active TB disease. Health education campaigns and community-based interventions can raise awareness about TB transmission, symptoms, and prevention measures and promote TB screening, diagnosis, and treatment services. Treatment for active TB involves combination antibiotic therapy with multiple drugs, typically lasting six to nine months, to eradicate the bacteria from the body and prevent disease relapse. Directly observed therapy (DOT) ensures medication adherence and treatment completion, reducing the risk of drug resistance and treatment failure. In cases of drug-resistant TB, including multidrug-resistant TB (MDR-TB) and extensively drug-resistant TB (XDR-TB), individualized treatment regimens with second-line drugs and prolonged treatment duration are necessary to achieve cure and prevent transmission.",

    'Common Cold': "The common cold is a viral respiratory infection caused by a variety of viruses, including rhinoviruses, coronaviruses, and adenoviruses, characterized by symptoms such as nasal congestion, runny nose, sore throat, coughing, and sneezing. Prevention of the common cold focuses on practicing good hygiene to reduce the risk of viral transmission and bolstering the immune system to minimize susceptibility to infection. Measures to prevent the common cold include frequent handwashing with soap and water, especially after coughing or sneezing, and avoiding close contact with individuals who are sick. Using alcohol-based hand sanitizers, covering the mouth and nose with a tissue or elbow when coughing or sneezing, and avoiding touching the face, particularly the eyes, nose, and mouth, can help reduce the spread of respiratory viruses. Health education campaigns and community-based interventions can raise awareness about the importance of respiratory etiquette, hand hygiene, and environmental cleanliness in preventing the common cold. Treatment for the common cold focuses on relieving symptoms and supporting the immune system's natural defense mechanisms. Over-the-counter medications such as analgesics (e.g., acetaminophen, ibuprofen) and decongestants (e.g., pseudoephedrine, phenylephrine) may be used to alleviate pain, fever, and nasal congestion. Antihistamines may help relieve symptoms such as sneezing and runny nose. However, antibiotics are not effective against viral infections like the common cold and should not be used unless there is evidence of bacterial co-infection or complications.",

    'Pneumonia': "Pneumonia is an inflammatory lung infection characterized by consolidation of lung tissue and impaired gas exchange, typically caused by bacterial, viral, or fungal pathogens. Prevention of pneumonia involves addressing risk factors for infection and implementing strategies to strengthen the immune system and reduce transmission of respiratory pathogens. Vaccination is a key preventive measure for pneumonia, with vaccines available for certain bacterial and viral pathogens commonly associated with pneumonia, including Streptococcus pneumoniae (pneumococcus), influenza virus, and respiratory syncytial virus (RSV). The pneumococcal conjugate vaccine (PCV13) and pneumococcal polysaccharide vaccine (PPSV23) provide protection against pneumococcal pneumonia and are recommended for children, adults over 65 years of age, and individuals with underlying medical conditions. Influenza vaccination is recommended annually for all individuals aged six months and older to reduce the risk of influenza-related pneumonia and complications. Good hygiene practices, such as frequent handwashing with soap and water, covering the mouth and nose when coughing or sneezing, and avoiding close contact with individuals who are sick, can help prevent the spread of respiratory pathogens that cause pneumonia. Smoking cessation, maintaining a healthy lifestyle, including balanced nutrition and regular exercise, and managing chronic medical conditions, such as asthma or chronic obstructive pulmonary disease (COPD), can help strengthen the immune system and reduce susceptibility to pneumonia. Treatment for pneumonia depends on the underlying cause and severity of infection and may involve antibiotics for bacterial pneumonia, antiviral medications for viral pneumonia, and supportive care to manage symptoms and promote recovery. Hospitalization may be necessary for individuals with severe pneumonia or underlying medical conditions that increase the risk of complications.",

    'Dimorphic hemorrhoids (piles)': "Dimorphic hemorrhoids, commonly known as piles, are swollen veins in the rectum and anus that cause discomfort, pain, itching, and bleeding during bowel movements. Prevention of hemorrhoids involves adopting lifestyle modifications and dietary changes to reduce the risk of developing hemorrhoids or exacerbating existing symptoms. Measures to prevent hemorrhoids include maintaining regular bowel habits, avoiding straining during bowel movements, and ensuring adequate fiber intake to promote soft, bulky stools and prevent constipation. Drinking plenty of water, engaging in regular physical activity, and avoiding prolonged sitting or standing can help improve bowel function and reduce the risk of hemorrhoid formation. Health education campaigns and community-based interventions can raise awareness about the importance of bowel health, proper toilet habits, and dietary factors in preventing hemorrhoids. Treatment for hemorrhoids focuses on symptom relief and promoting healing of inflamed tissues. Over-the-counter remedies such as topical creams, ointments, or suppositories containing corticosteroids, analgesics, or vasoconstrictors can help alleviate pain, itching, and inflammation associated with hemorrhoids. Sitz baths, warm water baths taken in a shallow basin or bathtub, can provide temporary relief by reducing swelling and promoting relaxation of the anal muscles. Lifestyle modifications, such as dietary changes, increased fluid intake, and regular exercise, can help improve bowel habits and reduce the risk of recurrent hemorrhoids. In severe cases or when conservative measures fail to provide relief, procedures such as rubber band ligation, sclerotherapy, infrared coagulation, or surgical excision may be recommended to remove or shrink hemorrhoidal tissue and alleviate symptoms.",
   
'Heart attack': "A heart attack, also known as a myocardial infarction (MI), occurs when blood flow to a part of the heart muscle is blocked, leading to damage or death of the heart tissue. Prevention of heart attacks involves addressing modifiable risk factors for cardiovascular disease and adopting heart-healthy lifestyle habits. Lifestyle modifications to prevent heart attacks include maintaining a healthy weight, following a balanced diet low in saturated fats, cholesterol, and sodium, quitting smoking, engaging in regular physical activity, and managing stress. Regular medical check-ups, including blood pressure and cholesterol screenings, can help identify cardiovascular risk factors early and initiate preventive measures. Treatment for heart attacks focuses on restoring blood flow to the affected part of the heart muscle to prevent further damage and improve outcomes. Emergency medical intervention, such as administering aspirin and nitroglycerin, and performing interventions such as percutaneous coronary intervention (PCI) or coronary artery bypass grafting (CABG), aims to reopen blocked arteries and restore blood flow. Medications such as antiplatelet agents, beta-blockers, ACE inhibitors, statins, and anticoagulants are prescribed to reduce the risk of recurrent heart attacks and manage underlying cardiovascular risk factors. Cardiac rehabilitation programs provide structured exercise training, lifestyle counseling, and education to help individuals recover from a heart attack, prevent future cardiovascular events, and improve overall health.",


    'Varicose veins': "Varicose veins are enlarged, swollen, and twisted veins, usually occurring in the legs and feet, due to weakened or damaged vein walls and valves. Prevention of varicose veins involves lifestyle modifications and self-care measures to improve blood circulation and reduce venous pressure in the legs. Measures to prevent varicose veins include maintaining a healthy weight, engaging in regular physical activity, avoiding prolonged standing or sitting, elevating the legs when resting, and wearing compression stockings to support vein function and prevent blood pooling. Avoiding tight clothing that constricts blood flow and high heels that strain calf muscles can also help reduce the risk of varicose veins. Health education campaigns and community-based interventions can raise awareness about venous health, promote lifestyle changes to prevent varicose veins, and provide information on available treatment options. Treatment for varicose veins focuses on relieving symptoms and improving vein function. Conservative measures such as lifestyle modifications, leg elevation, regular exercise, and wearing compression stockings can help alleviate discomfort and reduce swelling associated with varicose veins. Minimally invasive procedures such as sclerotherapy, laser therapy, or radiofrequency ablation may be recommended to close off or remove varicose veins and improve cosmetic appearance. In severe cases or when complications such as venous ulcers occur, surgical interventions such as vein ligation and stripping or ambulatory phlebectomy may be necessary to remove diseased veins and restore venous circulation.",

    'Hypothyroidism': "Hypothyroidism is a thyroid disorder characterized by inadequate production of thyroid hormones, leading to a slowdown in bodily functions and metabolism. Prevention of hypothyroidism involves addressing underlying causes and risk factors, as well as promoting thyroid health through lifestyle modifications and dietary measures. Measures to prevent hypothyroidism include consuming a balanced diet rich in iodine, selenium, and zinc, essential nutrients for thyroid hormone synthesis and function. Iodized salt, seafood, dairy products, eggs, nuts, and whole grains are good dietary sources of these nutrients. Avoiding excessive consumption of goitrogenic foods, such as cruciferous vegetables (e.g., cabbage, broccoli, kale), soy products, and certain fruits (e.g., peaches, strawberries), can help prevent interference with thyroid hormone production. Regular medical check-ups and thyroid function tests can help identify thyroid disorders early and initiate appropriate interventions. Treatment for hypothyroidism involves hormone replacement therapy with synthetic thyroid hormones, such as levothyroxine (T4), to restore normal thyroid hormone levels and alleviate symptoms. Medication adherence and regular monitoring of thyroid function tests are essential for optimizing treatment effectiveness and preventing complications. Lifestyle modifications, including maintaining a healthy weight, managing stress, getting regular exercise, and avoiding tobacco smoke and excessive alcohol consumption, can help support thyroid health and improve overall well-being for individuals with hypothyroidism.",

    'Hyperthyroidism': "Hyperthyroidism is a thyroid disorder characterized by excessive production of thyroid hormones, leading to an acceleration of bodily functions and metabolism. Prevention of hyperthyroidism involves identifying and addressing underlying causes and risk factors, as well as promoting thyroid health through lifestyle modifications and dietary measures. Measures to prevent hyperthyroidism include consuming a balanced diet rich in essential nutrients for thyroid function, such as iodine, selenium, and zinc. Iodized salt, seafood, dairy products, eggs, nuts, and whole grains are good dietary sources of these nutrients. Avoiding excessive iodine intake, particularly from supplements or iodine-rich foods, can help prevent thyroid dysfunction. Regular medical check-ups and thyroid function tests can help monitor thyroid health and detect abnormalities early. Treatment for hyperthyroidism depends on the underlying cause and severity of symptoms. Antithyroid medications such as methimazole or propylthiouracil may be prescribed to reduce thyroid hormone production and alleviate symptoms. Radioactive iodine therapy or thyroidectomy (surgical removal of the thyroid gland) may be recommended for individuals with persistent or severe hyperthyroidism. Close monitoring of thyroid function tests and regular follow-up with healthcare providers are essential for managing hyperthyroidism and preventing complications such as thyroid storm or thyroid eye disease.",

    'Hypoglycemia': "Hypoglycemia, also known as low blood sugar, occurs when blood glucose levels drop below normal, leading to symptoms such as shakiness, sweating, dizziness, confusion, and weakness. Prevention of hypoglycemia involves maintaining stable blood sugar levels through balanced nutrition, regular physical activity, medication management, and self-monitoring of blood glucose levels. Measures to prevent hypoglycemia in individuals with diabetes include consuming regular meals and snacks at consistent times, balancing carbohydrate intake with insulin or oral hypoglycemic medications, and adjusting medication doses based on blood glucose levels and activity levels. Monitoring blood glucose levels frequently, especially before and after meals, exercise, and sleep, can help identify and prevent episodes of hypoglycemia. Health education and self-management programs can empower individuals with diabetes to recognize symptoms of hypoglycemia, take appropriate corrective actions, and seek timely medical care when needed. Treatment for hypoglycemia involves consuming fast-acting carbohydrates, such as glucose tablets, fruit juice, or regular soda, to raise blood sugar levels quickly and alleviate symptoms. If severe hypoglycemia occurs, requiring assistance from others to treat or if unconsciousness develops, emergency glucagon injection or intravenous glucose may be necessary to raise blood sugar levels rapidly. Preventive measures, such as carrying glucose tablets or snacks, wearing medical alert identification, and informing family members, friends, and coworkers about hypoglycemia, can help individuals with diabetes manage the condition effectively and reduce the risk of serious complications.",

    'Osteoarthritis': "Osteoarthritis is a degenerative joint disease characterized by the breakdown of joint cartilage and underlying bone, leading to pain, stiffness, and impaired joint function. Prevention of osteoarthritis involves addressing modifiable risk factors, adopting joint-friendly lifestyle habits, and implementing strategies to preserve joint health and function. Measures to prevent osteoarthritis include maintaining a healthy weight, engaging in regular physical activity, and protecting joints from injury or excessive wear and tear. Exercise programs that focus on strengthening muscles, improving flexibility, and maintaining joint range of motion can help reduce joint pain and stiffness, improve mobility, and delay disease progression. Avoiding repetitive stress on joints, such as heavy lifting, high-impact activities, and prolonged kneeling or squatting, can help prevent joint injury and minimize the risk of osteoarthritis development. Health education and community-based interventions can raise awareness about joint health, promote lifestyle changes to prevent osteoarthritis, and provide information on available treatment options. Treatment for osteoarthritis focuses on relieving symptoms, preserving joint function, and improving quality of life. Nonpharmacologic interventions such as physical therapy, occupational therapy, and assistive devices can help manage pain, improve joint stability, and enhance mobility. Pain-relieving medications such as acetaminophen or nonsteroidal anti-inflammatory drugs (NSAIDs) may be used to alleviate symptoms. Intra-articular injections of corticosteroids or hyaluronic acid may be recommended for individuals with persistent pain or inflammation. Surgical interventions, such as joint replacement surgery or arthroscopic surgery, may be considered for individuals with advanced osteoarthritis or severe joint damage that does not respond to conservative treatments.",

        '(vertigo) Paroxysmal Positional Vertigo': "Paroxysmal positional vertigo (BPPV) is a common vestibular disorder characterized by brief episodes of dizziness and spinning sensations triggered by changes in head position. Prevention of BPPV involves identifying and avoiding triggers that can provoke vertigo episodes and implementing strategies to improve vestibular function and balance. Measures to prevent BPPV include avoiding sudden head movements or changes in head position that can trigger vertigo, such as bending over, looking up, or rolling over in bed. Using caution when getting out of bed or rising from a lying or sitting position can help minimize the risk of vertigo episodes. Health education and vestibular rehabilitation programs can provide individuals with strategies to manage BPPV symptoms, improve balance and coordination, and reduce the frequency and severity of vertigo episodes. Treatment for BPPV focuses on maneuvers to reposition displaced inner ear crystals (otoconia) that cause vertigo symptoms. Canalith repositioning maneuvers, such as the Epley maneuver or the Semont maneuver, are performed to move otoconia out of the affected semicircular canal and into the vestibule, where they can be absorbed or dissolved. Vestibular suppressant medications may be prescribed to alleviate symptoms of dizziness and nausea during vertigo episodes. Balance exercises, gaze stabilization exercises, and habituation exercises are incorporated into vestibular rehabilitation programs to help individuals adapt to changes in vestibular function and improve overall balance and mobility. Surgical interventions are rarely necessary for BPPV and are reserved for cases refractory to conservative treatments or when underlying vestibular pathology is present.",

    'Acne': "Acne is a common skin condition characterized by the formation of pimples, blackheads, whiteheads, and cysts on the face, neck, chest, back, and shoulders. Prevention of acne involves adopting good skincare practices, managing risk factors, and avoiding triggers that can exacerbate acne symptoms. Measures to prevent acne include washing the face twice daily with a gentle cleanser and lukewarm water to remove excess oil, dirt, and dead skin cells that can clog pores and contribute to acne formation. Avoiding harsh scrubbing or abrasive skincare products can help prevent irritation and inflammation of the skin. Using non-comedogenic or oil-free cosmetics, sunscreen, and skincare products can help minimize pore blockage and reduce the risk of acne breakouts. Avoiding touching or picking at acne lesions can prevent further inflammation, scarring, and bacterial spread. Health education and dermatology consultations can provide individuals with information about acne prevention, treatment options, and skincare routines tailored to their skin type and concerns. Treatment for acne depends on the severity and type of acne lesions and may include topical medications such as benzoyl peroxide, salicylic acid, retinoids, or antibiotics to reduce inflammation, unclog pores, and kill acne-causing bacteria. Oral medications such as oral contraceptives, antibiotics, or isotretinoin may be prescribed for moderate to severe acne that does not respond to topical treatments. Procedures such as chemical peels, microdermabrasion, laser therapy, or photodynamic therapy may be recommended for individuals with resistant or scarring acne lesions. Consistent skincare habits, regular follow-up with a dermatologist, and adherence to treatment regimens are essential for managing acne and preventing recurrence.",

    'Urinary tract infection': "A urinary tract infection (UTI) is a bacterial infection affecting the urinary system, including the kidneys, bladder, ureters, and urethra, commonly characterized by symptoms such as urinary urgency, frequency, burning with urination, and cloudy or bloody urine. Prevention of UTIs involves strategies to reduce the risk of bacterial colonization and infection of the urinary tract and promote urinary tract health. Measures to prevent UTIs include staying hydrated by drinking plenty of water to promote frequent urination and flush out bacteria from the urinary tract. Urinating shortly after sexual intercourse can help expel bacteria from the urethra and prevent their ascent into the bladder. Wiping from front to back after bowel movements can help prevent the spread of bacteria from the anal region to the urethra and reduce the risk of UTIs in women. Avoiding irritants such as feminine hygiene products, douches, and spermicides, which can disrupt the natural balance of vaginal flora and increase susceptibility to UTIs, is recommended. Health education and community-based interventions can raise awareness about UTI risk factors, symptoms, and preventive measures and provide information on appropriate hygiene practices and urinary tract health. Treatment for UTIs typically involves antibiotics to eradicate the causative bacteria and alleviate symptoms. Empiric antibiotic therapy is initiated based on the severity of symptoms, patient characteristics, and suspected bacterial pathogens, with adjustments made based on urine culture and sensitivity results. Analgesics such as phenazopyridine may be used to relieve urinary discomfort and pain. In recurrent UTIs or complicated cases, further evaluation, including imaging studies or urologic evaluation, may be necessary to identify underlying risk factors or anatomical abnormalities predisposing to UTIs.",

    'Psoriasis': "Psoriasis is a chronic autoimmune skin disorder characterized by the rapid proliferation of skin cells, leading to the formation of thickened, scaly, red patches (plaques) on the skin surface. Prevention of psoriasis involves managing triggers and risk factors that can exacerbate symptoms and implementing strategies to promote skin health and immune system balance. Measures to prevent psoriasis flares include avoiding known triggers such as stress, skin injury or trauma, infections, smoking, and excessive alcohol consumption. Maintaining a healthy lifestyle with regular exercise, balanced nutrition, adequate sleep, and stress management techniques can help support immune system function and reduce inflammation associated with psoriasis. Protecting the skin from excessive dryness or irritation by using moisturizers, gentle skincare products, and avoiding harsh chemicals or abrasive treatments is recommended. Health education and dermatology consultations can provide individuals with information about psoriasis triggers, treatment options, and self-care strategies tailored to their specific needs and preferences. Treatment for psoriasis aims to reduce inflammation, control symptoms, and prevent disease progression. Topical treatments such as corticosteroids, vitamin D analogs, retinoids, or calcineurin inhibitors may be used to reduce inflammation and promote skin healing. Phototherapy with ultraviolet (UV) light or systemic medications such as methotrexate, cyclosporine, or biologic agents may be prescribed for moderate to severe psoriasis that does not respond to topical treatments. Lifestyle modifications, adherence to treatment regimens, and regular follow-up with a dermatologist are essential for managing psoriasis and minimizing its impact on quality of life.",

    'Impetigo': "Impetigo is a highly contagious bacterial skin infection caused by Staphylococcus aureus or Streptococcus pyogenes bacteria, commonly affecting children and characterized by the formation of honey-colored crusts or fluid-filled blisters on the skin. Prevention of impetigo involves promoting good hygiene practices, implementing infection control measures, and reducing exposure to potential sources of bacterial transmission. Measures to prevent impetigo include washing the hands frequently with soap and water, especially after touching contaminated surfaces or skin lesions, and avoiding sharing personal items such as towels, clothing, or toys with individuals who have impetigo. Keeping skin clean and dry, avoiding scratching or picking at skin lesions, and covering open wounds or sores with clean band."
}
p=list(input_symptoms.split())
for i in range(len(syy)):
    if syy[i] in p:
        input_attributes[i]=1
import datetime

def append_lime_explanation_to_html(model, data_row,user_input,xai_response):
    # Generate Lime explanation
    explainer = lime_tabular.LimeTabularExplainer(xtrain.values, feature_names=X.columns, class_names=['prognosis'], discretize_continuous=True)
    exp = explainer.explain_instance(np.array(data_row), model.predict_proba, num_features=len(X.columns))
    html_explanation = exp.as_html()
    
    # Append Lime explanation to HTML file
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    with open("lime_explanations.html", "a", encoding="utf-8") as f:
        f.write(f"<div><strong>User: </strong>{user_input}</div>")
        f.write(f"<div><strong>XAI: </strong>{xai_response}</div>")
        f.write(f"<div><strong>Time:</strong> {timestamp}</div>")
        f.write(html_explanation)
        f.write("<hr>")  # Add a horizontal line for separation
    with open("conversation_log.txt", "a") as g:
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        g.write(f"Time: {timestamp}\n")
        g.write(f"User: {user_input}\n")
        g.write(f"XAI: {xai_response}\n\n")

if(input_attributes.count(1) <= 2 ):
    print("Please provide some more information")
else:
    predicted_disease = predict_disease(model_rf, input_attributes)
    lime_html_file = append_lime_explanation_to_html(model_rf, input_attributes,input_symptoms,predicted_disease)
    print(f"{predicted_disease}")
    print()
    print(f"Diagnosis: {disease_dict[predicted_disease]}")





